### PR TITLE
Hide directive

### PR DESCRIPTION
**Pull request by pespantelis**
It is the opposite of `show` directive.

### CODE REVIEW

**Comment by azamat-sharapov** [comment]
Doesn't this make API more verbose and add more size to library? Why not just `v-show="!show"`?

**Comment by pespantelis** [comment]
IMO `v-hide="show"` is more clean and readable from `v-show="!show"`.
Regarding the library, it is increased less than half of KB.

**Comment by yyx990803** [comment]
Thanks for the PR, but let me explain why I don't want to add `v-hide`: the general philosophy behind Vue is we want to keep it as lightweight as possible, so when we add code into the codebase, we want to make sure the code either provides substantial improvement to an existing feature, or adds a new functionality that cannot be trivially achieved with the current API. In general, we want to avoid adding code just for the sake of stylistic alternatives. In fact we have been trying to removing stylistic alternatives as much as possible (e.g. `v-with` vs `props`).

`v-hide`, in my opinion, is just a stylistic alternative to `v-show`, and its benefit over `v-show` is somehow subjective and marginal.

Regardless, thanks for your PR and hope to see you contributing to Vue again in the future :)

**Comment by pespantelis** [comment]
Thank you for the detailed explanation :)

**Pull request closed without merging**
