### PR TITLE
support define a watcher whose key is symbol * to watch all properties of data

### PR DESCRIPTION
**Pull request by zhongxingdou**

### CODE REVIEW

**Comment by zhongxingdou** [comment]
example
```javascript
new Vue({
    data: {
        name: "hal",
        age: 30
    },
    watch: {
       "*": function(prop, newVal, val){
            console.log(prop + " changed: " + val + " --> " + newVal);
       }
   }
})
```

**Comment by TMiguelT** [comment]
I'm not at my computer to check this but can't you just watch "$data" with Vue to the same effect?

**Comment by TMiguelT** [comment]
Ah no you can't! +1 Although perhaps watch $data might be more intuitive. 
http://jsfiddle.net/4qs8kkan/1/

**Comment by yyx990803** [comment]
But this would not trigger on nested data changes, right?

**Pull request closed without merging**
