### PR TITLE
Add objects support to v-attr

### PR DESCRIPTION
**Pull request by OEvgeny**
The goal is to add to ``v-attr`` directive support for objects:
```
<div v-attr="obj"></div>
```
Demo here: http://jsfiddle.net/nd9baygn/3/

Waiting for suggestions patiently :)

### CODE REVIEW

**Comment by yyx990803** [comment]
Looking good! Let's just make things consistent to resemble the updated `v-style` implementation: https://github.com/yyx990803/vue/blob/dev/src/directives/style.js

I think the logic should be equivalent and I don't see the need to store the previous object as `this.obj`.

**Comment by Nirazul** [comment]
The demo does not seem to work in latest Chrome.

**Comment by OEvgeny** [comment]
Done!

**Comment by yyx990803** [comment]
good job!

**Pull request merged**
